---
name: devcontainer-ci

on:
    push:
        paths:
            - .github/workflows/devcontainer-ci.yml
            - images/iggy-cpp-build/.devcontainer/*

env:
    DOCKERHUB_REGISTRY_NAME: iggyrs/iggy-cpp-build

permissions: read-all

jobs:
    pre-build-container:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Setup Docker buildx for multi-architecture builds
              uses: docker/setup-buildx-action@v3
              with:
                  use: true
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Pre-build image
              uses: devcontainers/ci@v0.3
              with:
                  subFolder: images/iggy-cpp-build
                  imageName: ${{ env.DOCKERHUB_REGISTRY_NAME }}
                  cacheFrom: ${{ env.DOCKERHUB_REGISTRY_NAME }}
                  platform: linux/amd64,linux/arm64
                  push: always
